### ISSUE TITLE
ALMNH ES Create an Arctos Team

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#109]
Follow instructions at [How To Create and Manage Your Arctos Team: Users and Operators](http://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html)

**Comment by Jegelewicz** [comment]
@mbprondzinski please read this and get Kevin added as an operator for your collection.

**Comment by kmkocot** [comment]
That's me.

**Comment by Jegelewicz** [comment]
@kmkocot I just realized - is your collection part of the paleo stuff or is it Invert Zoo?

**Comment by kmkocot** [comment]
I only work on squishy things - it's Invertebrate Zoology, not Invertebrate Paleontology. Thanks!

**Comment by Jegelewicz** [comment]
Well, then that's a whole new can of worms (tee hee)! The FIRST thing we need to do is get a portal created for your collection in Arctos. I am going to set up a data migration project just for your collection, then I'll send instructions on the next step.

**Comment by Jegelewicz** [comment]
> That’s how I want them entered.  Chelsea entered herself in that column, not me (she entered the data in the spreadsheet).  

Only those with the ability to enter data can be in the "Entered By" field. If you want to have Chelsea be the "entered by" agent, she needs to be an Arctos Operator. You'll need to add her to your Arctos team following the instructions above. Once she has the appropriate access, I can put her name in the entered by field.

**Comment by mbprondzinski** [comment]
I don't think Chelsea is part of the "Arctos team" by a long shot.  This was the only data entry she performed (in the field for Ike) and she will not be entering data again.  By all means put me down as the data entry person if it is that discriminatory.  She entered the data in the spreadsheet, but I cleaned up the fields and passed it on to you for uploading.  She is in Arctos as an Agent, however, from previous collecting trips.

**Comment by mbprondzinski** [comment]
"No one has ever told me that you needed these collections! I would have asked to have them created along with the others if I had known. It would be best if you requested these yourself. Just follow this link and fill out the form. No need to be super-detailed when answering all of the institutional questions since we already know who you are."

I got to thinking that with all the collections being created for us, why not have the mammals, birds and herps added as well?  True, they aren't huge collections, but I am always using specimens related to those collections for in-house loans and events, so what the heck?!  I'll bet you a thousand dollars I will have data input in those collections before anyone else does anything with the collections you've created for the others.

**Comment by campmlc** [comment]
Hi Mary Beth,
what is the status on your fish collection?

**Comment by mbprondzinski** [comment]
Hi Mariel,

Our extant fish collection is under the control of Biological Sciences and is in Specify.  We (the museum) have a comparative osteology collection that has extant fish in it, but is generally only used by the Paleontologist.  We have a couple of trophy mounted fish in the taxidermy as well.

We have a herpetology collection that is partially under Biological Sciences and partially under us, but I don’t think John Abbott realizes that, though I’ve mentioned it to him.  There are also taxidermied specimens.

If we aren’t going to use Filemaker anymore, how else can I keep track of this stuff?!   Do we get charged by the collection or the number of records?  That would be my question.

Thanks, Mariel

**Comment by campmlc** [comment]
Sounds like you are doing the right thing. Fee is per record, not by number
of collections.
