### ISSUE TITLE
3. ALMNH ES Verts - Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#27]
This issue will be used to resolve issues with ALMNH agents.

**Comment by Jegelewicz** [comment]
@mbprondzinski I need to clear up something in your agent names.

I have assumed when a collector was listed as Kidd and S. Shannon, that there is a collector named Kidd Shannon, but there is a collector with the name Jack T. Kidd who seems to have worked with Sam Shannon (S. Shannon) and now I wonder if all of the Kidd references in Kidd and Shannon are actually referring to Jack T. Kidd. Is there a collector named Kidd Shannon or should all those refer to Jack T. Kidd?

Thanks!

**Comment by mbprondzinski** [comment]
Hi Teresa,

Apparently, Jack T. Kidd and Sam Shannon worked together at the GSA.   There is no Kidd Shannon.  (Shame on the person who entered it that way!)  There are lots of problem entries like that, I’m afraid, which is why I will have to go back over EVERYTHING I have ALREADY gone over once you get it all into Arctos.  That is also why I am unhappy about all this.  I have the data,  I have the files, but I can’t make any changes to it because you are handling all that.  There are too many problems for me to relay to you and my not being able to make the changes when I find them is only compounding my work.  That collection was definitely not ready for prime time.

I have finished all the accessions and emailed the entire file to you last week.  (You need only be concerned with 1986 -1999.) There are definite problems there as well, but again, I could not make any changes.  They weren’t things you could do, either.  I also sent you an updated Agents file, which I highlighted in yellow.  Any name that isn’t highlighted in any color is either wrong, or I couldn’t find them in any printed reference.

BTW,  I still don’t know how the “ALMNH PaleoVertebrate Collection” finally got categorized under “Other Identifier Type” on the Arctos home/search page.  I have read all the handbook, I have looked up the code table where it pre-existed, but someone (Dusty?) managed to include it in the drop down menu for that field after I gave up trying to figure out how to add it myself.  Here is my question:  Can I add those search terms or does Dusty have to do it?  Someone had to have added the “GSA: Geological Survey,” and other categories listed in that field…was that you?  If you understand what I am talking about, then just answer me this:  Can I add those search terms myself????

Thanks…
Mary Beth

**Comment by dustymc** [comment]
FWIW in my experience data can only be about as good as the system. For every problem you fix in the system that created those problems in the first place, or in some spreadsheet between that system and Arctos, you'll make new problems. (Often lots of them!)

Arctos has a ton of tools to deal with this sort of thing (the "agent deconcatenator" is built just for this), and in "real Arctos" they're easy to find and easy to fix.

There is great value in consistency. If you are fixing things eg, after Dave (the 'migrators' just make things more consistent) and before Arctos, you are probably making the data less consistent and thereby harder to get into Arctos. 

I'm not sure where you are in the overall process, but in my view the ONLY possible way to deal with any sort of problem between VertNet and the pre-bulkloader is to toss the whole mess and start over; minor problems with individual records must be fixed either before VertNet or in the pre-bulkloader. Anything else provides a pathway for not-so-minor problems to slip in.

The "search terms" are simply ID types. You can create them by adding them (and their corresponding values) to specimen records. You can use the bulk-deleter to remove IDs and the bulk-loader to create them, which provides a path to change the types of any number of records.

**Comment by Jegelewicz** [comment]
> BTW, I still don’t know how the “ALMNH PaleoVertebrate Collection” finally got categorized under “Other Identifier Type” on the Arctos home/search page. I have read all the handbook, I have looked up the code table where it pre-existed, but someone (Dusty?) managed to include it in the drop down menu for that field after I gave up trying to figure out how to add it myself. Here is my question: 

That problem was caused by me. I had labeled all of the PV numbers as "original identifier" instead of "ALMNH PaleoVertebrate Collection”. It was pretty easy for Dusty to switch them for us. (thanks @dustymc !)

> Can I add those search terms or does Dusty have to do it? Someone had to have added the “GSA: Geological Survey,” and other categories listed in that field…was that you? If you understand what I am talking about, then just answer me this: Can I add those search terms myself????

The available other ID "search terms" are listed in the [Other Identifiers code table](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE). Only those with the ability to edit the code tables (which are shared by ALL Arctos collections) can make those changes. All you need to do is post a GitHub issue if you need a new value.

**Comment by mbprondzinski** [comment]
AAAaahhhhh!  Thank you, Teresa!

**Comment by Jegelewicz** [comment]
> Apparently, Jack T. Kidd and Sam Shannon worked together at the GSA. There is no Kidd Shannon. (Shame on the person who entered it that way!) There are lots of problem entries like that, I’m afraid, which is why I will have to go back over EVERYTHING I have ALREADY gone over once you get it all into Arctos. That is also why I am unhappy about all this. I have the data, I have the files, but I can’t make any changes to it because you are handling all that. There are too many problems for me to relay to you and my not being able to make the changes when I find them is only compounding my work. That collection was definitely not ready for prime time.

I think this is a pretty easy fix - any reference to "Kidd Shannon" is actually a reference to Jack T. Kidd. All I have to do is make Kidd Shannon a duplicate of Jack T. Kidd and everything will resolve!  This is where having the data in Arctos actually makes it EASIER to correct.

Dusty makes a valid point above and in reality, no one's data is EVER "ready for prime time". Don't be unhappy and don't let these little things get you down. Every thing we find as we go along is making the data better!

**Comment by Jegelewicz** [comment]
I'll get those new agents in as I run across them and I'll work on the remaining accessions after I have uploaded the specimen records for the 2000-2017 accessions.
