### ISSUE TITLE
6. NMMNH Inv - Taxonomy (Classifications)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#39]
Read the [Taxonomy](http://handbook.arctosdb.org/documentation/taxonomy.html) documentation

For any names that were added in the previous data migration step, there will not be a related classification in any of the local Arctos taxonomy sources. For a small number of new names, these can be created manually by following the instructions in [How To Create Taxa](http://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html). To create a large number of classifications, use the [Bulkload Taxonomy Classifications Tool](http://arctos.database.museum/tools/BulkloadClassification.cfm)

**Comment by lin-fred** [comment]
Need to add to arctos or something:

Agarica agaricites
Amphidromus cambojiensis
Anthocardia tuberculata

Caucasicola raddei - in WORMS but not in Arctos?

And continue looking at the rest of the taxonomy issues in paulas notes

/remind me Friday

**Comment by Jegelewicz** [comment]
Agarica agaricites should be spelled Agaricia agaricites

**Comment by Jegelewicz** [comment]
Amphidromus cambojiensis added to Arctos

**Comment by Jegelewicz** [comment]
Anthocardia tuberculata should be Acanthocardia tuberculata?

**Comment by Jegelewicz** [comment]
Caucasicola raddei added to Arctos

**Comment by lin-fred** [comment]
Thanks Teresa for getting on top of those!

Here is more:

Retinella nitens - https://mczbase.mcz.harvard.edu/guid/MCZ:Mala:228281
Retinella sculptilis - http://www.marinespecies.org/aphia.php?p=taxdetails&id=1366578
Stenotrema exodon turbinella - https://en.wikipedia.org/wiki/Stenotrema
Tectarius cumingii luchuana - might need to be Tectarius cumingii {Tectarius cumingii luchuana}
Thiaropsis scabra
Ampullaria   ampullacea var. pila

**Comment by Jegelewicz** [comment]
Retinella nitens - added with relationship to Aegopinella nitens per [GBIF](https://www.gbif.org/species/9885907)

Retinella sculptilis - added with classification and aphiaid

Stenotrema exodon turbinella - hmmmm, not too confident in this. I say use Stenotrema exodon {Stenotrema exodon turbinella}

Tectarius cumingii luchuana - agree, use Tectarius cumingii {Tectarius cumingii luchuana}

Thiaropsis scabra - perhaps [Triodopsis scabra](http://www.marinespecies.org/aphia.php?p=taxdetails&id=1365659)

Ampullaria ampullacea var. pila - I don't find any evidence for this, except that Ampullaria ampullacea is a synonym for Pila ampullacea, I would say use Ampullaria ampullacea with Ampullaria ampullacea var. pila in the ID remark. The relationship between the two names already exists in Arctos.

**Comment by lin-fred** [comment]
Thiaropsis scabra  - I put it as Triodopsis scabra {Thiaropsis scabra}...it just scares me how wrong the potential misspelling is, or if it is some obscure genus

Ampullaria ampullacea {Ampullaria ampullacea var. pila}?

**Comment by Jegelewicz** [comment]
> Ampullaria ampullacea {Ampullaria ampullacea var. pila}?

Yep, that's fine too.

**Comment by lin-fred** [comment]
Chondrothyretes reticulata seems to exist but nothing great

**Comment by lin-fred** [comment]
Columna flammea - https://en.wikipedia.org/wiki/Columna_(gastropod)

Dentalium sexcostatum - https://www.gbif.org/species/4628500

Dendrotrochus intercalata - this one is weird, seems to be one that is sold

Diloma zebrina - seems like a rabbit hole one

Euconulus chersinus dentatus - https://www.carnegiemnh.org/science/mollusks/va_euconulus_dentatus.html

Eulota peliomphala septentrionalis

[Eulota quaesita](https://books.google.com/books?id=jq-TImE5AcoC&pg=RA1-PA196&lpg=RA1-PA196&dq=Eulota+quaesita&source=bl&ots=uIs4-wlEIO&sig=ACfU3U3Nl7eBTQKdpWgxcBdU3sxLGkw_BQ&hl=en&sa=X&ved=2ahUKEwjXz9a3q-_mAhUPS6wKHTEPBO4Q6AEwAXoECAoQAQ#v=onepage&q=Eulota%20quaesita&f=true)

[Eutrochatella regina](https://books.google.com/books?id=OUtPAQAAMAAJ&pg=RA1-PA138&lpg=RA1-PA138&dq=Eutrochatella+regina&source=bl&ots=mcTPKMdN-H&sig=ACfU3U3JrYWF7gj2Ch03X3sm4nm7eFsGsg&hl=en&sa=X&ved=2ahUKEwiF7rGUtO_mAhXDna0KHUcSCPQQ6AEwAnoECAoQAQ#v=onepage&q=Eutrochatella%20reg&f=false)

**Comment by lin-fred** [comment]
@Jegelewicz are you able to give your second opinion on the taxonomy above when you get the chance? Thanks!!

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/taxonomy.html#overview

"The google test" - search for the string in quotes - is, I think, usually close enough for Arctos.

https://www.google.com/search?q=%22Chondrothyretes+reticulata%22
 seems real enough

https://www.google.com/search?q=%22Diloma+zebrina%22

<img width="440" alt="Screen Shot 2020-02-10 at 8 35 09 AM" src="https://user-images.githubusercontent.com/5720791/74169496-44f6bd80-4be0-11ea-974c-226046b8f32b.png">


almost certainly isn't real, or even a useful misspelling/combination/whatever it's supposed to be.

(But definitely "almost" - folks have tracked down paper records for a few of those!)

**Comment by Jegelewicz** [comment]
Chondrothyretes reticulata - added to arctos with synonym relationship to Chondrothyra reticulata

**Comment by Jegelewicz** [comment]
Columna - is an ["uncertain" name](http://www.irmng.org/aphia.php?p=taxlist&searchpar=0&tComp=begins&tName=Columna&genera_only=on&rComp=%3D&tRank=180&action=search&rSkips=0&adv=0), but added this anyway as other Columna are already in Arctos.

**Comment by Jegelewicz** [comment]
Dentalium sexcostatum - added

**Comment by Jegelewicz** [comment]
Dendrotrochus intercalata - added based upon [this](https://commons.wikimedia.org/wiki/File:Naturalis_Biodiversity_Center_-_RMNH.MOL.282744_1_-_Dendrotrochus_intercalata_Rensch_-_Chronidae_-_Mollusc_shell.jpeg), using classification from previously existing Dendrotrochus.

**Comment by Jegelewicz** [comment]
Diloma zebrina - suggest Diloma {Diloma zebrina}

**Comment by Jegelewicz** [comment]
Euconulus chersinus dentatus 

The link you have is to [Euconulus dentatus](https://www.carnegiemnh.org/science/mollusks/va_euconulus_dentatus.html) and I can't find anything about subspecies anywhere.

Suggest using

Euconulus chersinus or Euconulus dentatus

**Comment by lin-fred** [comment]
on [Euconulus chersinus dentatus](https://www.carnegiemnh.org/science/mollusks/va_euconulus_dentatus.html) a little further down the page it has: "This species has also been known as Euconulus chersinus dentatus." I've added the subspecies and put it as as invalid, and as a synonym for Euconulus dentatus

**Comment by Jegelewicz** [comment]
Eulota peliomphala septentrionalis

This is an ["unaccepted" genus](http://www.marinespecies.org/aphia.php?p=taxdetails&id=956181) but no reference to the species or sub-species.

[Euhadra peliomphala](https://arctos.database.museum/name/Euhadra%20peliomphala) is a thing though and based upon some of the Google results, seems like these might have crossed paths at some point. I don't see that subspecies anywhere though.

Suggest

Euhadra peliomphala {Eulota peliomphala septentrionalis}

**Comment by Jegelewicz** [comment]
Eulota quaesita = [Euhadra quaesita](https://arctos.database.museum/name/Euhadra%20quaesita)

suggest

Euhadra quaesita {Eulota quaesita}

**Comment by Jegelewicz** [comment]
Eutrochatella regina - added, but I'm guessing this is a synonym or something because one reference in an article seems a bit thin for a species name that is so common they "cease to gather it"!

**Comment by Jegelewicz** [comment]
Ferrissia arkansasensis - added with synonym relationship and aphiaid

**Comment by lin-fred** [comment]
When I add a mollusc to Arctos, do I add it to the Arctos source or the WoRMS (via Arctos) source?

**Comment by Jegelewicz** [comment]
Add it to WoRMS (via Arctos) since that is the taxonomy source you are using for inverts.

**Comment by sharpphyl** [comment]
I've been away (vacation) from this thread.  I was unaware anyone else was adding taxa to WoRMS (via Arctos) and I really want to keep it as pristine as possible.   

_Eutrochatella regina_ was abundant in 1914 (per the source you quote) but the odds are that the genus has changed.  Eutrochatella is in the family Helicinidae.  Is it possible that your specimens are _Viana regina_ (Morelet, 1849)?  (You can find this by doing an "advanced search" in WoRMS.  Remember that terrestrial species are less well represented in WoRMS so not all valid taxa are included - but every week more and more are added.  I think most of the species in this thread are terrestrial which is why they are not yet in WoRMS (via Arctos) which is why any collection with terrestrial mollusks will frequently need to add taxa.  Also, there is much less agreement on terrestrial taxonomy so we need to decide who (what institution or sources) we think are most valid and try to stick with them.  

I would like to make a request that no taxon name be added
1) without a valid source authority
2) without an author
3)  if it is invalid unless there is a flaming reason to add it.

For example, there is no author on the _Eutrochatella regina_ entry.  If it is Morelet, then it's likely that the current genus is Viana.  If it's some other author, then Viana is unlikely and we need to do more research.  

I'd also like to have procedures that we always add a new species by cloning the WoRMS (via Arctos) genus so that the higher classification is always the same.

@Jegelewicz Teresa, can we add this to our agenda for Wednesday and set up some guidelines?  I'm paranoid about WoRMS (via Arctos) slowly acquiring the same problems that Arctos and Arctos Plants have and that I spent months of my life trying to clean up before we were able to switch over to WoRMS (via Arctos).

Also, Teresa, what do you mean by _Euhadra quaesita {Eulota quaesita}_.

@dustymc Dusty, now that multiple institutions are adding and modifying WoRMS (via Arctos), can we get a daily report (like we get for new Higher Geography) that lists the taxon classifications added. to WoRMS (via Arctos).  I can decide if I want to look over the entry or not, but at least I know what's being added and the other users of WoRMS (via Arctos) can see what I add as well.

**Comment by Jegelewicz** [comment]
@dustymc If WoRMS (via Arctos) needs to be duplicated so that DMNS can keep their source the way they want it kept, can we do that?

**Comment by dustymc** [comment]
@sharpphyl not immediately - it's not really set up the same as geography. It seems reasonable to want to keep this clean, I'm sure we can figure something out - new Issue.

Has anyone asked WoRMS about being a contributor? That seems like an obvious readily-available filter, and "if it doesn't have a resolvable aphiaid then it's garbage" would be a much easier report to write.

Euhadra quaesita {Eulota quaesita} is A {string} from http://handbook.arctosdb.org/documentation/bulkloader.html#taxonomy

**Comment by sharpphyl** [comment]
> Euhadra quaesita {Eulota quaesita} is A {string} from http://handbook.arctosdb.org/documentation/bulkloader.html#taxonomy

Thanks for the link.  As the  accepted taxon followed by the verbatim taxon, is it an identification or does it create a name in our taxon tables?  The handbook reads "Any of the following are acceptable taxon name values..."

What do GBIF and iDigBio etc. do with a string like this?  

I'll start a new issue requesting some way to monitor what we add to WoRMS (via Arctos) after we have our committee meeting tomorrow.  Thanks.

As for us being a contributor, I certainly cannot be an authority for them.  Most of the terrestrial species names are coming from https://www.molluscabase.org/ which is led by Gary Rosenberg Drexel University; Academy of Natural Sciences and other experts in the field -https://www.molluscabase.org/aphia.php?p=editors.

**Comment by dustymc** [comment]
Euhadra quaesita {Eulota quaesita} links to taxon name Euhadra quaesita and displays Eulota quaesita. There's no magical authority creation involved!

>What do GBIF and iDigBio etc. do

Something weird, probably!

I'm not suggesting anyone specific, just that that someone who want to use WoRMS (via Arctos) as a source might first work with WoRMS before duct-taping stuff off the side in Arctos. "Here's a big well-curated database, import please" seems like the best way to do that sort of thing.

**Comment by Jegelewicz** [comment]
> 
> 
>     What do GBIF and iDigBio etc. do
> 
> Something weird, probably!

See https://github.com/ArctosDB/arctos/issues/2172

**Comment by Jegelewicz** [comment]
> As for us being a contributor, I certainly cannot be an authority for them. Most of the terrestrial species names are coming from https://www.molluscabase.org/ which is led by Gary Rosenberg Drexel University; Academy of Natural Sciences and other experts in the field -https://www.molluscabase.org/aphia.php?p=editors.

I agree - I am no expert and "curating" implies more expertise in my opinion!

**Comment by lin-fred** [comment]
Looking to add subspecies Polygyra postelliana espiloca
Finding it here: https://www.biodiversitylibrary.org/item/21394#page/49/mode/1up

**Comment by sharpphyl** [comment]
If you look at page 2 (text) in the BHL they say that they only mapped subspecies that showed a "sharp differentiation" and they only mapped _Polygyra postelliana_ and not the subspecies _P. p. espiloca_.  I would interpret that to mean that they don't recognize the subspecies. See Page also 148, figure 368 which only shows a map for _Polygyra postelliana._  So per this source, you would probably use _Polygyra postelliana_ without the subspecies.  You may read the paragraph on page 2 differently, but that's my interpretation.  

A better resource is WoRMS because it's more recent (vs. 1985) and they have updated the genus.  See _Daedalochila postelliana_ (Bland, 1859) aphiaID 1352324 at http://www.marinespecies.org/aphia.php?p=taxdetails&id=1352324 and you'll see that a synonym is _Helix espiloca_ Bland, 1860 which may have been the original designation before it was moved to Polygyra.  I find there are frequently gaps between each name change but as long as your specimen looks like others with identified as _Daedalochila postelliana_ (see http://bioweb.uwlax.edu/bio210/s2012/kerrigan_kara/ for an excellent overview and images of the species) I would go with that and you won't need to add a new taxon name.  BTW, WoRMS also lists five sources they used, so you could check them out if you need further information.

**Comment by lin-fred** [comment]
How do we deal with "unknown" taxonomy. Do I need to classify it under Animalia or is there an unknown option?

**Comment by campmlc** [comment]
There is an "unknown" option, but if you know at least Animalia that
separates out all the plants and cultural items.

**Comment by Jegelewicz** [comment]
It isn't "unknown" it is "unidentifiable", but yes to what Mariel says! I would only use unidentifiable if you literally do not know what the heck it is....

**Comment by lin-fred** [comment]
Ah thanks! I had tried unknown and it didn't work. I'll use unidentifiable. 

I don't think I'll be able to identify them, it says it was identified by Rick Smartt. They'll be on my list to find and look at to see what's going once we're back

**Comment by campmlc** [comment]
Rick Smartt implies Mollusca, doesn't it?

**Comment by jldunnum** [comment]
He actually did a bunch of Peromyscus diet work way back when....

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Likely Animalia is a safe bet then.

**Comment by campmlc** [comment]
Or plantae. sigh. I guess Eukaryota is probably not realistic.

**Comment by dustymc** [comment]
>Or plantae. sigh. I guess Eukaryota is probably not realistic.

Sure it is - http://arctos.database.museum/name/Eukaryota. That's not terribly precise, but it still excludes the vast majority of things that might end up cataloged in Arctos.
